M5 db in-memory and cassandra
crowdproj/crowdproj-comments pull request #7
Opened 2023-12-18 12:30 UTC by StellaLupus

2023-12-19 04:37 UTC, svok approved these changes
Андрей, отличная работа

2023-12-19 04:39 UTC, svok requested changes
Стоп. У вас куда-то делася ci. Добавьте пожалуйста .github с файлами сборки и надо убедиться, что все тесты проходят в независимом сборщике.

2023-12-20 16:42 UTC, StellaLupus commented
Добавил тестирование на github

2023-12-21 05:21 UTC, svok approved these changes

2023-12-21 07:42 UTC, svok requested changes
Все-таки не работает

2023-12-21 11:14 UTC, svok approved these changes

2023-12-21 11:14 UTC, merged